name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create data asset if not exists
      run: |
        echo $workspace
        az ml data show --name diabetes-dev-folder -v 1 $jobs-demo 2> /dev/null || az ml data create --name diabetes-dev-folder --version 1 --path ./experimentation/data $jobs-demo
    - name: Create a job
      run: |
        # replace compute name variable
        cd src
        export computeName=${{ vars.computeClusterName }}
        cat job.yml | envsubst '${ci-jobs}' | tee job-updated.yml
        # create a job
        az ml job create --file job-updated.yml $jobs-demo
