on:
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: merge pull request
        run: |
            echo "Will add code checks here in next challenge"
