name: Model training job using GitHub Environments

on:
  workflow_dispatch:

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: development_env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    - name: Model training
      run: az ml job create -f src/job-dev.yml --resource-group cloud-shell-storage-centralindia --workspace-name jobs-demo 

  train-prod:
    runs-on: ubuntu-latest
    environment: production_env
    needs: train-dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    - name: Model training
      run: az ml job create -f src/job-prod.yml --resource-group cloud-shell-storage-centralindia --workspace-name jobs-demo 

